// resources/js/Pages/Auth/Login.tsx
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { FormEvent } from 'react';
import { FieldError } from '../../Components/UI';
import { Page } from '../../types';

export default function Login() {
  const { flash } = usePage<Page>().props;
  const form = useForm({ email: '', password: '', remember: false });
  const submit = (e: FormEvent) => { e.preventDefault(); form.post(route('login')); };
  return <AuthShell title="Welcome back">
    <Head title="Login" />{flash.status && <p className="mb-3 text-sm text-teal-700">{flash.status}</p>}
    <form onSubmit={submit} className="space-y-4">
      <div><label className="label">Email</label><input className="field mt-1" type="email" value={form.data.email} onChange={e => form.setData('email', e.target.value)} autoFocus /><FieldError message={form.errors.email} /></div>
      <div><label className="label">Password</label><input className="field mt-1" type="password" value={form.data.password} onChange={e => form.setData('password', e.target.value)} /><FieldError message={form.errors.password} /></div>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.remember} onChange={e => form.setData('remember', e.target.checked)} /> Remember this device</label>
      <button className="btn btn-primary w-full" disabled={form.processing}>Log in</button>
    </form>
    <div className="mt-5 flex justify-between text-sm"><Link href={route('password.request')}>Forgot password?</Link><Link href={route('register')}>Create account</Link></div>
  </AuthShell>;
}

export function AuthShell({ title, children }: { title: string; children: React.ReactNode }) {
  return <main className="grid min-h-screen place-items-center bg-stone-100 px-4 dark:bg-zinc-950"><section className="w-full max-w-md"><div className="mb-6"><h1 className="text-3xl font-semibold">ProgressOS</h1><p className="mt-2 text-zinc-600 dark:text-zinc-400">Personal operating system for progress, learning, and work review.</p></div><div className="card p-6"><h2 className="mb-5 text-xl font-semibold">{title}</h2>{children}</div></section></main>;
}

// resources/js/vue/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { RouterLink, useRouter } from 'vue-router';
import { useAuthStore } from '../stores/auth';

const auth = useAuthStore();
const router = useRouter();
const error = ref('');
const form = ref({ email: 'test@example.com', password: 'password', remember: true });

async function submit() {
  error.value = '';
  try {
    await auth.login(form.value);
    await router.push('/dashboard');
  } catch (e: any) {
    error.value = e.response?.data?.message || 'Login failed.';
  }
}
</script>

<template>
  <main class="grid min-h-screen place-items-center bg-stone-100 px-4">
    <section class="w-full max-w-md">
      <div class="mb-6"><h1 class="text-3xl font-semibold">ProgressOS</h1><p class="mt-2 text-zinc-600">Personal operating system for progress, learning, and work review.</p></div>
      <form class="card space-y-4 p-6" @submit.prevent="submit">
        <h2 class="text-xl font-semibold">Welcome back</h2>
        <p v-if="error" class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{ error }}</p>
        <label><span class="label mb-1">Email</span><input v-model="form.email" class="field" type="email" required /></label>
        <label><span class="label mb-1">Password</span><input v-model="form.password" class="field" type="password" required /></label>
        <label class="flex items-center gap-2 text-sm"><input v-model="form.remember" type="checkbox" /> Remember this device</label>
        <button class="btn btn-primary w-full">Log in</button>
        <RouterLink to="/register" class="block text-center text-sm font-semibold text-teal-700">Create account</RouterLink>
      </form>
    </section>
  </main>
</template>
