// resources/js/Pages/Projects/Index.tsx
import { Head, Link } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import { Empty, PageHeader, Stat } from '../../Components/UI';

export default function Index({ projects }: any) {
  return <AppLayout><Head title="Projects" /><PageHeader title="Projects" />
    {projects.length === 0 ? <Empty text="Projects appear automatically when work logs or tasks use a project name." /> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{projects.map((project: any) => <Link key={project.id} href={route('projects.show', project.id)} className="card p-4 hover:border-teal-400 sm:p-5"><h2 className="text-lg font-semibold">{project.name}</h2><div className="mt-4 grid grid-cols-3 gap-2"><Stat label="Open" value={project.open_tasks_count} tone="sky" /><Stat label="Tasks" value={project.tasks_count} /><Stat label="Logs" value={project.work_logs_count} tone="teal" /></div></Link>)}</div>}
  </AppLayout>;
}

// resources/js/vue/views/Projects.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RouterLink } from 'vue-router';
import { api, unwrap } from '../api';

const projects = ref<any[]>([]);
onMounted(async () => projects.value = (await api.get('/api/v1/projects').then(unwrap)).projects);
</script>

<template>
  <div class="mb-5"><h1 class="text-2xl font-semibold">Projects</h1><p class="mt-1 text-sm text-slate-500">Project workspaces powered by REST API data.</p></div>
  <div v-if="projects.length === 0" class="card p-8 text-center text-sm text-slate-500">Projects appear when tasks or work logs use a project.</div>
  <div v-else class="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
    <RouterLink v-for="project in projects" :key="project.id" :to="`/projects/${project.id}`" class="card p-5 hover:border-teal-400">
      <h2 class="text-lg font-semibold">{{ project.name }}</h2>
      <div class="mt-4 grid grid-cols-3 gap-2 text-center text-sm">
        <div class="rounded-lg bg-slate-50 p-3"><b>{{ project.open_tasks_count }}</b><p class="text-slate-500">Open</p></div>
        <div class="rounded-lg bg-slate-50 p-3"><b>{{ project.tasks_count }}</b><p class="text-slate-500">Tasks</p></div>
        <div class="rounded-lg bg-slate-50 p-3"><b>{{ project.work_logs_count }}</b><p class="text-slate-500">Logs</p></div>
      </div>
    </RouterLink>
  </div>
</template>
