// resources/js/Pages/Auth/Register.tsx
import { Head, Link, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';
import { FieldError } from '../../Components/UI';
import { AuthShell } from './Login';

export default function Register() {
  const form = useForm({ name: '', email: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC', password: '', password_confirmation: '' });
  const submit = (e: FormEvent) => { e.preventDefault(); form.post(route('register')); };
  return <AuthShell title="Create your workspace"><Head title="Register" /><form onSubmit={submit} className="space-y-4">
    {(['name', 'email', 'timezone'] as const).map((key) => <div key={key}><label className="label">{key.replace('_', ' ')}</label><input className="field mt-1" value={form.data[key]} onChange={e => form.setData(key, e.target.value)} /><FieldError message={form.errors[key]} /></div>)}
    <div><label className="label">Password</label><input className="field mt-1" type="password" value={form.data.password} onChange={e => form.setData('password', e.target.value)} /><FieldError message={form.errors.password} /></div>
    <div><label className="label">Confirm password</label><input className="field mt-1" type="password" value={form.data.password_confirmation} onChange={e => form.setData('password_confirmation', e.target.value)} /></div>
    <button className="btn btn-primary w-full" disabled={form.processing}>Register</button>
  </form><p className="mt-5 text-sm"><Link href={route('login')}>Already have an account?</Link></p></AuthShell>;
}

// resources/js/vue/views/Register.vue
<script setup lang="ts">
import { ref } from 'vue';
import { RouterLink, useRouter } from 'vue-router';
import { useAuthStore } from '../stores/auth';

const auth = useAuthStore();
const router = useRouter();
const error = ref('');
const form = ref({ name: '', email: '', password: '', password_confirmation: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC' });

async function submit() {
  error.value = '';
  try {
    await auth.register(form.value);
    await router.push('/dashboard');
  } catch (e: any) {
    error.value = e.response?.data?.message || 'Registration failed.';
  }
}
</script>

<template>
  <main class="grid min-h-screen place-items-center bg-stone-100 px-4">
    <form class="card w-full max-w-md space-y-4 p-6" @submit.prevent="submit">
      <h1 class="text-2xl font-semibold">Create ProgressOS account</h1>
      <p v-if="error" class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{ error }}</p>
      <label><span class="label mb-1">Name</span><input v-model="form.name" class="field" required /></label>
      <label><span class="label mb-1">Email</span><input v-model="form.email" class="field" type="email" required /></label>
      <label><span class="label mb-1">Timezone</span><input v-model="form.timezone" class="field" /></label>
      <label><span class="label mb-1">Password</span><input v-model="form.password" class="field" type="password" required /></label>
      <label><span class="label mb-1">Confirm password</span><input v-model="form.password_confirmation" class="field" type="password" required /></label>
      <button class="btn btn-primary w-full">Register</button>
      <RouterLink to="/login" class="block text-center text-sm font-semibold text-teal-700">Back to login</RouterLink>
    </form>
  </main>
</template>
