// resources/js/Pages/Auth/ResetPassword.tsx
import { Head, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';
import { FieldError } from '../../Components/UI';
import { AuthShell } from './Login';

export default function ResetPassword({ email, token }: { email: string; token: string }) {
  const form = useForm({ email, token, password: '', password_confirmation: '' });
  const submit = (e: FormEvent) => { e.preventDefault(); form.post(route('password.store')); };
  return <AuthShell title="Set new password"><Head title="Reset Password" /><form onSubmit={submit} className="space-y-4"><input type="hidden" value={token} /><div><label className="label">Email</label><input className="field mt-1" value={form.data.email} onChange={e => form.setData('email', e.target.value)} /><FieldError message={form.errors.email} /></div><div><label className="label">Password</label><input className="field mt-1" type="password" value={form.data.password} onChange={e => form.setData('password', e.target.value)} /><FieldError message={form.errors.password} /></div><div><label className="label">Confirm password</label><input className="field mt-1" type="password" value={form.data.password_confirmation} onChange={e => form.setData('password_confirmation', e.target.value)} /></div><button className="btn btn-primary w-full">Update password</button></form></AuthShell>;
}

// resources/js/vue/views/ResetPassword.vue
<script setup lang="ts">
import { ref } from 'vue';
import { RouterLink, useRoute, useRouter } from 'vue-router';
import { api } from '../api';

const route = useRoute();
const router = useRouter();
const form = ref({ token: String(route.params.token || ''), email: String(route.query.email || ''), password: '', password_confirmation: '' });
const error = ref('');

async function submit() {
  error.value = '';
  try {
    await api.post('/api/reset-password', form.value);
    await router.push('/login');
  } catch (e: any) {
    error.value = e.response?.data?.message || 'Could not reset password.';
  }
}
</script>

<template>
  <main class="grid min-h-screen place-items-center bg-stone-100 px-4">
    <section class="w-full max-w-md">
      <div class="mb-6"><h1 class="text-3xl font-semibold">ProgressOS</h1><p class="mt-2 text-zinc-600">Choose a new password.</p></div>
      <form class="card space-y-4 p-6" @submit.prevent="submit">
        <h2 class="text-xl font-semibold">Reset password</h2>
        <p v-if="error" class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{ error }}</p>
        <label><span class="label mb-1">Email</span><input v-model="form.email" class="field" type="email" required /></label>
        <label><span class="label mb-1">New password</span><input v-model="form.password" class="field" type="password" required /></label>
        <label><span class="label mb-1">Confirm password</span><input v-model="form.password_confirmation" class="field" type="password" required /></label>
        <button class="btn btn-primary w-full">Reset password</button>
        <RouterLink to="/login" class="block text-center text-sm font-semibold text-teal-700">Back to login</RouterLink>
      </form>
    </section>
  </main>
</template>
